export const TAG_NAMES = [
  'chest', 'back', 'shoulders', 'legs', 'glutes', 'arms',
  'biceps', 'triceps', 'core', 'calves', 'push', 'pull',
] as const

export type SeedExercise = { name: string; tags: string[] }

export const SEED_EXERCISES: SeedExercise[] = [
  // From the digitized 5-day plan
  { name: 'Leg curl (seated or lying)', tags: ['legs'] },
  { name: 'Hack squat', tags: ['legs'] },
  { name: 'Sumo squat', tags: ['legs', 'glutes'] },
  { name: 'Leg press', tags: ['legs'] },
  { name: 'Leg extension', tags: ['legs'] },
  { name: 'Lying leg raises', tags: ['core'] },
  { name: 'Standing calf raise', tags: ['calves', 'legs'] },
  { name: 'Squat', tags: ['legs', 'glutes'] },
  { name: 'Walking lunges', tags: ['legs', 'glutes'] },
  { name: 'Single leg hip thrust', tags: ['glutes', 'legs'] },
  { name: 'Sit ups', tags: ['core'] },
  { name: 'Plank', tags: ['core'] },
  { name: 'Incline smith machine press', tags: ['chest', 'push'] },
  { name: 'Incline cable fly', tags: ['chest', 'push'] },
  { name: 'Machine fly', tags: ['chest', 'push'] },
  { name: 'Dumbbell press soft decline', tags: ['chest', 'push'] },
  { name: 'Shoulder dumbbell press', tags: ['shoulders', 'push'] },
  { name: 'Shoulder machine press', tags: ['shoulders', 'push'] },
  { name: 'Lateral raises', tags: ['shoulders'] },
  { name: 'Incline dumbbell Y raise', tags: ['shoulders'] },
  { name: 'Front rope raise', tags: ['shoulders'] },
  { name: 'Incline dumbbell curl', tags: ['biceps', 'arms'] },
  { name: 'Reverse barbell curl', tags: ['biceps', 'arms'] },
  { name: 'Preacher curl machine', tags: ['biceps', 'arms', 'pull'] },
  { name: 'Rope overhead extension', tags: ['triceps', 'arms', 'push'] },
  { name: 'Single arm push down', tags: ['triceps', 'arms', 'push'] },
  { name: 'V-bar push down', tags: ['triceps', 'arms', 'push'] },
  { name: 'Upper abs plated', tags: ['core'] },
  { name: 'T-bar row wide grip', tags: ['back', 'pull'] },
  { name: 'Seated row narrow grip', tags: ['back', 'pull'] },
  { name: 'Lat pull down wide grip', tags: ['back', 'pull'] },
  { name: 'Seated face pull', tags: ['shoulders', 'back', 'pull'] },
  { name: 'Incline dumbbell shrug row', tags: ['back', 'pull'] },
  { name: 'Hyperextension weighted', tags: ['back', 'glutes'] },
  // Common staples
  { name: 'Bench press', tags: ['chest', 'push'] },
  { name: 'Deadlift', tags: ['back', 'legs', 'pull'] },
  { name: 'Romanian deadlift', tags: ['legs', 'glutes', 'pull'] },
  { name: 'Pull ups', tags: ['back', 'pull'] },
  { name: 'Barbell curl', tags: ['biceps', 'arms'] },
  { name: 'Overhead press', tags: ['shoulders', 'push'] },
  { name: 'Dips', tags: ['chest', 'triceps', 'push'] },
  { name: 'Cable crunch', tags: ['core'] },
]

export const SEED_WARMUPS: string[] = [
  'Body weight squats 2 sets x 10',
  'Hip airplanes 2x12',
  'Reverse snow angels (scapular retraction)',
  'Hip mobility drills, dynamic stretches',
  'Band shoulder dislocates 10 rep x 3',
  'Face pulls 2x20 / light DB lateral raises',
  'Dynamic stretch (arm circles forward and backward)',
  'Dead hang',
  'Scap pull-ups 2x12',
  'Band pull aparts 2x20',
  'Cat cow stretch',
  'Cobra stretch',
  'Jefferson curl 10kg',
  'Plank 1 min constant',
]
